import "~/styles/globals.css"

import { Inter } from "next/font/google"

import { TRPCReactProvider } from "~/trpc/react"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import CssBaseline from '@mui/material/CssBaseline'

import { ThemeProvider } from '@mui/material/styles'
import { StyledEngineProvider } from '@mui/material/styles'
// import theme from '~/theme';
import { getServerAuthSession } from "~/server/auth"

import AppBar from '@mui/material/AppBar'
import Toolbar from '@mui/material/Toolbar'
import Typography from '@mui/material/Typography'
import Button from '@mui/material/Button'
import { Avatar } from "@mui/material"
import LayoutMenu from "./_components/LayoutMenu"
import type { Metadata } from 'next'

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // 能否在此处注入session provider?
  const session = await getServerAuthSession()
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-KTZQFVDM');
            `,
          }}
        ></script>
      </head>
      <body className={`font-sans ${inter.variable}`} id="__next">
        <noscript>
          <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KTZQFVDM" height="0" width="0" style={{display: 'none', visibility: 'hidden'}}></iframe>
        </noscript>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            window._AMapSecurityConfig = {
              securityJsCode: "3747a561489d91f0878157f6933dde4c",
            }
            `,
          }}
        ></script>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          {/* <ThemeProvider theme={theme}> */}
            {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
            {/* <StyledEngineProvider injectFirst> */}
              <CssBaseline />
              <TRPCReactProvider>
                <div className="flex flex-col">
                  <header className="flex bg-white justify-between">
                  <AppBar position="static">
                    <Toolbar>
                      <LayoutMenu></LayoutMenu>
                      { session ? 
                        <a href="/user" className="block">
                          <Avatar src={session?.user.image || ''} alt="avatar"></Avatar>
                        </a>
                        :
                        <Button color="inherit" href="/login">Sign in</Button>
                      }
                    </Toolbar>
                  </AppBar>
                  </header>
                  {children}
                </div>
              </TRPCReactProvider>
            {/* </StyledEngineProvider> */}
          {/* </ThemeProvider> */}
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
