import "~/styles/globals.css"

import { Inter } from "next/font/google"

import { TRPCReactProvider } from "~/trpc/react"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import CssBaseline from '@mui/material/CssBaseline'

import { ThemeProvider } from '@mui/material/styles'
import { StyledEngineProvider } from '@mui/material/styles'
// import theme from '~/theme';
import { getServerAuthSession } from "~/server/auth"

import AppBar from '@mui/material/AppBar'
import Toolbar from '@mui/material/Toolbar'
import Typography from '@mui/material/Typography'
import Button from '@mui/material/Button'
import { Avatar } from "@mui/material"
import LayoutMenu from "./_components/LayoutMenu"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession()
  console.log('layout ', session)
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`} id="__next">
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          {/* <ThemeProvider theme={theme}> */}
            {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
            {/* <StyledEngineProvider injectFirst> */}
              <CssBaseline />
              <TRPCReactProvider>
                <div className="flex flex-col">
                  <header className="flex bg-white justify-between">
                  <AppBar position="static">
                    <Toolbar>
                      <LayoutMenu></LayoutMenu>
                      <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                        Create t3 app
                      </Typography>
                      { session ? 
                        <a href="/user" className="block">
                          <Avatar src={session?.user.image || ''} alt="avatar"></Avatar>
                        </a>
                        :
                        <Button color="inherit" href="/login">Sign in</Button>
                      }
                    </Toolbar>
                  </AppBar>
                  </header>
                  {children}
                </div>
              </TRPCReactProvider>
            {/* </StyledEngineProvider> */}
          {/* </ThemeProvider> */}
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
